### ISSUE TITLE
Pi/ARM: Install script produces Bad Gateway

### ISSUE THREAD

**Issue by ghost** [SeafileDE/seafile-server-installer#78] opened 2016-04-10 01:41 UTC
Using the Ubuntu Trusty (Pi/ARM) install script the final result is Bad Gateway in the browser.
I can provide the seafile-ce_ubuntu-trusty-arm_installation.log if necessary.

If the local IP address is used it produces Bad Gateway 
If the Domain Name is used server DNS address could not be found. DNS_PROBE_FINISHED_NXDOMAIN

Running seafile-server-change-address does not mitigate the issue.

**Comment by flames** [comment] 2016-04-22 09:59
Same error message on Debian Jessie 8.4.

But here the issue is in the database setup portion of the script. The password parameter is not passed to the mysqladmin/mysql cli tools, so we get access denied on user/db/table creation. W/o correct db setup seafile/seahub services do not start. Result is, there is nothing to listen on for Nginx = Bad Gateway.

After setting up db manually, seafile started and works perfectly.

**Comment by nymilator** [comment] 2017-04-14 20:30
I have the same Problem, i have installed it on and odroid an now it displays bad gateway in the browser.
Is still no solution available?

**Comment by alexanderjackson** [comment] 2017-05-30 11:12
This installer is deprecated and no longer supported. I'm closing the issue.

**Closed as completed by alexanderjackson** 2017-05-30 11:12 UTC
